First PR4
RomanGuys/Sprint_3 pull request #4
Opened 2021-11-24 23:40 UTC by RomanGuys

2021-11-26 19:52 UTC, NickFlexer commented on src/test/java/AcceptOrderTestMethods.java
> +    private String baseURI = "https://qa-scooter.praktikum-services.ru/api/v1/orders/accept/";
Часть url https://qa-scooter.praktikum-services.ru/api/v1 повторяется для всех методов. Ее можно вынести отдельно. Тогда, если сервер сменится, достаточно будет поменять только одну строку

2021-11-26 19:55 UTC, NickFlexer commented on src/test/java/CreateCourierTests.java
> +        ArrayList<String> data = new ArrayList(Arrays.asList("testatest","glop","gaf"));
Название data  стоит переименовать на что-то более говорящее

2021-11-26 19:56 UTC, NickFlexer commented on src/test/java/CourierUsingPostMethods.java
> +    Response courierAddResponse;
Почему поле класса не приватное?

2021-11-26 19:57 UTC, NickFlexer commented on src/test/java/CourierUsingPostMethods.java
> +    public void courierAdd(ArrayList<String> courierData){
Можно просто возвращать Response из этого метода, не используя поле класса

2021-11-26 20:00 UTC, NickFlexer commented on src/test/java/CreateCourierTests.java
> +
В методе createCourierPositiveTest ты удаляешь созданного курьера, а в этом - нет. Подумай, как можно сделать так, чтобы курьер удалялся для всех тестов на его создание?

2021-11-26 20:01 UTC, NickFlexer commented on src/test/java/CreateCourierTests.java
> +    public void createCourierWORequiredFieldNameTest(){
В приложенном Allure-отчете этот тест упал. Нужно исправить - посмотри в чем проблема и устрани ее. Все тесты должны быть "зелеными"

2021-11-26 20:04 UTC, NickFlexer commented on src/test/java/CreateOrderTestMethods.java
> +    String defaultOrderData = "{\n" +
Более правильным решением будет хранить тестовые данные в коде самих тестов, а не во вспомогательном коде

2021-11-26 20:05 UTC, NickFlexer commented on src/test/java/CreateOrderTests.java
> +    private static String orderBodyTwoColors = "{\n" +
Поля класса лучше располагать над методами

2021-11-26 20:07 UTC, NickFlexer commented on src/test/java/GetOrdersListTests.java
> +        getOrderTestMethods.getOrderResponse.then()
Стоит добавить проверку статус-кода ответа

2021-11-26 20:10 UTC, NickFlexer requested changes
Добрый день!

Общие замечания:

Ты создал несколько классов с названиями типа ...TestMethods - к ним сразу несколько претензий:
- это очень плохой нейминг.  Классы зачастую содержат только по одному методу, но называются ...Method**s**. Вообще, лучше переименовать эти классы, так как их названия не описывают их назначения. Почему это тестовые методы, если они ничего не проверяют?
- в чем смысл этих классов? Если описать вспомогательные методы, которые вызываются в тестовом коде, то стоит перенести код в java/main и оформить аналогично page objects из предыдущего спринта

В Allure-отчет стоит добавить что-то еще кроме названия тестов. Например, лог запроса и ответа от сервиса. Так же, в сложных тестах удобно разбивать действия на шаги (аннотации @Step в Allure). Подумай, как можно дополнить твой отчет

2021-11-27 11:57 UTC, RomanGuys commented on src/test/java/CreateCourierTests.java
> +    public void createCourierWORequiredFieldNameTest(){
Тест падает, так как курьер создается без имени, что некорректно по постановке

2021-12-03 21:37 UTC, NickFlexer approved these changes
Добрый день! У меня больше замечаний нет. Работа зачтена

2021-12-06 21:02 UTC, merged